### ISSUE TITLE
Does not sync instances when running on my machine

### ISSUE THREAD

**Issue by fivestones** [vlcn-io/live-examples#1]
I did git clone for the repository. Then I did npm install, and after installing, did npm run start:ui. When i load the page in my browser, it looks good and works to add and check off items from the to do list. But if I load the same page in a different browser, I have a separate instance with no syncing between them.

This kind of syncing works fine in the instance deployed to fly.dev. How can I make it work on my machine too?

Thanks!

**Comment by tantaman** [comment]
For client->server sync, you'll need to start the server as well.

`pnpm start:dev`

Looks like I didn't include a peer discovery server in this repository for the p2p example so let me add that for the p2p example.

**Comment by fivestones** [comment]
That was all I needed. It's working great now. Thanks!
